describe('template spec', () => {
 it('passes', () => {
cy.visit('https://automationteststore.com/index.php?rt=account/login')
cy.Customer('Ninokobakhidze', 'ninokobakhidze26')
let num=Math.round(Math.random() * 10000)
cy.visit('https://automationteststore.com/index.php?rt=account/edit')
cy.get('input[id="AccountFrm_firstname"]').clear()
cy.get('input[id="AccountFrm_firstname"]').type('Nino')
cy.get('input[id="AccountFrm_lastname"]').clear()
cy.get('input[id="AccountFrm_lastname"]').type('Kobakhidze');
cy.get('input[id="AccountFrm_email"]').clear()
cy.get('input[id="AccountFrm_email"]').type('ninokobakhidze26@gmail.com')
cy.get('input[id="AccountFrm_telephone"]').clear()
cy.get('input[id="AccountFrm_telephone"]').type('123456789');
cy.get('input[id="AccountFrm_fax"]').clear()
cy.get('input[id="AccountFrm_fax"]').type('987654321')
cy.get('button[title="Continue"]').click()
cy.contains('Success: Your account has been successfully updated.').should('be.visible')
cy.visit('https://automationteststore.com/index.php?rt=account/address')
cy.visit('https://automationteststore.com/index.php?rt=account/address/insert')
cy.get('input[id="AddressFrm_firstname"]').type('Nino')
cy.get('input[id="AddressFrm_lastname"]').type('Kobakhidze')
cy.get('input[id="AddressFrm_company"]').type('LLL')
cy.get('input[id="AddressFrm_address_1"]').type('123 Main Street')
cy.get('input[id="AddressFrm_address_2"]').type('Apt 4B')
cy.get('input[id="AddressFrm_city"]').type('Tbilisi')
cy.get('select[id="AddressFrm_country_id"]').select('Georgia')
cy.get('select[id="AddressFrm_zone_id"]').select('Tbilisi')
cy.get('input[id="AddressFrm_postcode"]').type('12345')
cy.get('button[title="Continue"]').click()
cy.contains('Your address has been successfully inserted').should('be.visible')
cy.get('button[title="Delete"]').click()
cy.contains('Your address has been successfully deleted').should('be.visible')
cy.visit('https://automationteststore.com/index.php?rt=account/password')
cy.get('input[id="PasswordFrm_current_password"]').type('ninokobakhidze26')
cy.get('input[id="PasswordFrm_password"]').type('ninokobakhidze26')
cy.get('input[id="PasswordFrm_confirm"]').type('ninokobakhidze26')
cy.get('button[title="Continue"]').click()
cy.contains('Success: Your password has been successfully updated.').should('be.visible')
  })
})